app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls', namespace="app1")),
]

app1/urls.py
from django.urls import path

from . import views

app_name = "app1"

urlpatterns = [
    path('upload', views.upload, name='upload'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('student/<int:student_id>', views.student, name='student'),
    path('Pending_Requests',views.Pending_Request, name='Pending_Request'),
    ]

app1/models.py
from django.db import models
from django.db.models import Model
from django.contrib.auth.models import User
from django import forms


# Create your models here.


class Department(models.Model):
    Department_Name = models.CharField(max_length=100,unique=True)


class Student(models.Model):
    first_name = models.CharField(max_length=100)
    last_name  = models.CharField(max_length=100)
    department = models.ForeignKey(Department,on_delete=models.CASCADE)

   


class demo(models.Model):
    name = models.CharField(max_length=100)
    age = models.CharField(max_length=100)
    gender = models.CharField(max_length=100)

class Profile(models.Model):
    Role_Choices = [
        ('Ta','Ta'),
        ('Manager','Manager'),
        ('Admin','Admin'),
    ]
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    role = models.CharField(
        max_length=10,
        choices=Role_Choices,
        default='Ta'
        )

class Pending_Requests(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    username=models.CharField(max_length=100)
    email=models.EmailField(max_length=100,blank=True)
    password=models.CharField(max_length=100)
    role = models.CharField(max_length=50,default = 'Ta')
    def __str__(self):
        return self.first_name

app1/views.py
from django.shortcuts import render,redirect
from app1.models import Profile,Student,Pending_Requests
from django.contrib.auth.models import User, auth
#import . from models
import openpyxl


def upload(request):
    if "GET" == request.method:
        return render(request, 'upload.html', {})
    else:
        excel_file = request.FILES["excel_file"]
        wb = openpyxl.load_workbook(excel_file)

        worksheet = wb["Sheet1"]
        print(worksheet)

        excel_data = list()

        for row in worksheet.iter_rows():
            print(int(row[0].value))
            print(str(row[1].value))
            p=Student.objects.create(number   =  int(row[0].value))

            p.first_name = str(row[1].value)
            p.last_name = str(row[2].value)
            p.department = str(row[3].value)
            p.save()
            print(p.number) 


        for row in worksheet.iter_rows():
            row_data = list()
            for cell in row:
                row_data.append(str(cell.value))
            excel_data.append(row_data)

        return render(request, 'upload.html', {"excel_data":excel_data})



def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        role=request.POST['role']
        password1 = request.POST['password1']
        password2 = request.POST['password2']


       # Admin = User.objects.create_user(username='Admin',password='a',email='admin@gmail.com',first_name='Admin',last_name='m')
       # Admin.save()
       # user_dummy =User.objects.create_user(first_name = first_name,last_name=last_name,username=username,email=email,password = password1)
       # user_dummy.save()
        Pending_Requests.objects.create(first_name = first_name,last_name=last_name,username=username,email=email,password = password1,role =role)
        #Admin_profile=Profile.objects.create(user = Admin,role='Admin')
        
        # pro.start_No=41
        # pro.end_No=44

      
        # pro.save()
        # print("hi")

        # print(pro.role)
        # print(pro.user.username)

        #add messages latter
        return redirect('/login')
    else:
        return render(request,'register.html')


def login(request):
    if(request.method=="POST"):
        print("check_2")
        username=request.POST['username']
        password=request.POST['password']

        user=auth.authenticate(username=username,password=password)
        request_ta = list()
        request_manager = list()
        for r in Pending_Requests.objects.all():
            if(r.role == 'Ta'):
                stud1 = r
                request_ta.append(stud1)
            if(r.role == "Manager"):
                stud2 = r
                request_manager.append(stud2)    
        
                

        if user is not None:
            auth.login(request,user)
            actual_user = Profile.objects.get(user=user)
            i=0
            print (actual_user.role)
            if(actual_user.role=='Ta'):
                i=i+1
                return render(request,'ta_dashboard.html',{'user':actual_user},)

            #     #code for ta
            #     arr = list()
            #     for num in range(actual_user.start_No,actual_user.end_No+1):

            #         stu = Student.objects.get(number=num)
            #         print(stu.first_name)
            #         arr.append(stu) 

            # #print(arr[0].first_name)

            #     return render(request,'ta_dashboard.html',{'user':actual_user,"arr":arr})
            
            elif(actual_user.role=='Manager'):
                i=i+1
                #code for manager
                return render(request ,'manager_dashboard.html',{ "request_ta":request_ta })
            else:
                i=i+1
                #code for admin
                return render(request ,'admin_dashboard.html',{ "request_manager":request_manager })

           
            #return render(request ,'manager_dashboard.html',{ "request_ta":request_ta })
            
        else:
            print('invalid Credentials')
            return render(request,'login.html')
    else:
        print("check4")
        return render(request,'login.html')


def student(request,student_id):
    if(request.method=="GET"):
        user=auth.get_user(request)
        if(user.is_authenticated):
            actual_user = Profile.objects.get(user=user)
            if(actual_user.start_No<=student_id or actual_user.end_No>=student_id):
                stu=Student.objects.get(number=student_id)
                return render(request,'student.html',{'user':actual_user,'student':stu})
            else:
                return redirect('/login')
                #this redirection supposed to be changed 

        #    return redirect('/login')
        #print("jii")
        else:
            return redirect('/login')


    else:
        discrepency=request.POST.get('discrepency')
        
        comment=request.POST['comment']
        stu=Student.objects.get(number=student_id)
        stu.check_box='Yes'
        print(stu.discrepency)
        if(str(discrepency)=='on'):
            stu.discrepency='Yes'
        else:
            stu.discrepency='No'


        print(stu.discrepency)
        stu.comment=comment
        stu.save()
        user=auth.get_user(request)
        actual_user = Profile.objects.get(user=user)
        arr=list()
        for num in range(actual_user.start_No,actual_user.end_No+1):
            student = Student.objects.get(number=num)
            print(student.first_name)
            arr.append(student)

        return render(request,'ta_dashboard.html',{'user':actual_user,"arr":arr})



    








def logout(request):
    print(auth.get_user(request).username)

    print("logout working")
    auth.logout(request)
    print(auth.get_user(request).username)
    if(auth.get_user(request).is_authenticated):
        print("hii")
    else:
        print("bye")
    return redirect('/login')

def Pending_Request(request):
        if request.method == 'POST':
            for r in Pending_Requests.objects.all():
                r.status = request.POST.get(r.username)

                if (r.status == 'ACCEPT'):
                    user_dummy = User.objects.create_user(username=r.username,password=r.password,email=r.email,first_name=r.first_name,last_name=r.last_name)
                    user_dummy.save()
                    pro = Profile(user = user_dummy,role = r.role)
                    pro.save()
                    r.delete()
                if (r.status == 'REJECT'):
                    
                    r.delete()


             
        request_ta = list()
        request_manager = list()             

        for r in Pending_Requests.objects.all():
                if(r.role == 'Ta'):
                    stud1 = r
                    request_ta.append(stud1)
                if(r.role == "Manager"):
                    stud2 = r
                    request_manager.append(stud2) 
        
        ROLE = request.POST.get('ROLE', None)
                      
        if(ROLE == 'Admin'):
            return render(request ,'admin_dashboard.html',{ "request_manager":request_manager })
        else:
            return render(request ,'manager_dashboard.html',{ "request_ta":request_ta})
         
         
       


                
                

app1/templates/admin_dashboard.html
<!DOCTYPE html>
<html>
<head>
<title>ADMIN</title>
</head>
<body>
<form action = 'Pending_Requests' method = 'post' > 
        {% csrf_token %}  
 <p> Pending requests </p>
 

{% for r in request_manager  %}  
    {{ r.first_name }} &emsp;
     
    
    <label for="ACCEPT">ACCEPT</label>
    <input type="radio" name= {{ r.username }} id="ACCEPT" value="ACCEPT">
    <label for="REJECT">REJECT</label>
    <input type="radio" name= {{ r.username }} id="REJECT" value="REJECT"><br>

{% endfor %}  
    <input type="hidden" id = 'id'   name="ROLE" value="Admin"> 
    <input type="submit" value="Submit">
<form>
</br> <a href="/logout">logout</a>

</body>
</html>

app1/templates/index.html
<html>
    <head>
        <title>
            Excel file upload and processing : Django Example : ThePythonDjango.Com
        </title>
    </head>
    <body style="margin-top: 30px;margin-left: 30px;">
        <form action="{% url "app1:upload" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>

        <p></p>
        <hr>

        {% for row in excel_data %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}
    </body>
</html>

app1/templates/login.html
<!DOCTYPE html>
<html>
<head>

</head>
<body>
    <form action="login" method="post">
        {% csrf_token %}
        
        
        <input type="text" name="username" placeholder= 'username' ><br>
        <input type="password" name="password" placeholder="password"><br>
        <input type="Submit">
    </form>
</body>
</html>

app1/templates/manager_dashboard.html
<!DOCTYPE html>
<html>
<head>
<title>MANAGER</title>
</head>
<body>
<form action = 'Pending_Requests' method = 'post' > 
        {% csrf_token %}
 <p> Pending requests </p>
{% for r in request_ta  %}
    {{ r.first_name }} &emsp;   
    

    <label for="ACCEPT">ACCEPT</label>
    <input type="radio" name= {{ r.username }} id="ACCEPT" value="ACCEPT">
    <label for="REJECT">REJECT</label>
    <input type="radio" name= {{ r.username }} id="REJECT" value="REJECT"><br>

{% endfor %}   
    <input type="hidden" id = 'id' name="ROLE" value="Manager">
    <input type="submit" value="Submit">
<form>
   </br> <a href="/logout">logout</a>



</body>
</html>

app1/templates/register.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Registration</title>

</head>
<body>

    <form action="register" method="post">{% csrf_token %}
    <input type="text" name="first_name" placeholder="first_name"><br>
    <input type="text" name="last_name" placeholder="last_name"><br>
    <input type="text" name="username" placeholder="UserName"><br>
    ROLE:<BR/>
        <label for="ta">TA</label>
        <input type="radio" name="role" id="ta" value="Ta"><br>
        <label for="manager">MANAGER</label>
        <input type="radio" name="role" id="manager" value="Manager"><br>
        
       
    <input type="email" name="email" placeholder="Email"><br>
    <input type="password" name="password1" placeholder="pswd"><br>
    <input type="password" name="password2" placeholder="confirm pswd"><br>


    <input type="Submit">
    </form>
</body>
</html>  

app1/templates/student.html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>
    <p> hii</p>
    <p> {{user.user.username}}</p>

    <a href="/logout">logout</a>

    <p>{{student.first_name}}</p>
    <p>{{student.last_name}}</p>

    <form action="{% url "app1:student" student_id=student.number %}" method="post">
        {% csrf_token %}
        <input type="checkbox" id="discrepency" name="discrepency">
        <label for="discrepency">Discrepency</label><br>
        <input type="text" name="comment" placeholder="type the comment here">
        <input type="Submit">
    </form>

    
 
    <html><html>
        <head>
        <head>


</body>
</html>

app1/templates/ta_dashboard.html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>
    <p> hii</p>
    <p> {{user.user.username}}</p>

    <a href="/logout">logout</a>
    {% for stu in arr  %}
        hii
        <a href= "{% url "app1:student" student_id=stu.number %}">{{stu.first_name}}</a><br>
    {% endfor %}

 



</body>
</html>

app1/templates/upload.html
<html>
    <head>
        <title>
            Excel file upload and processing : Django Example : ThePythonDjango.Com
        </title>
    </head>
    <body style="margin-top: 30px;margin-left: 30px;">
        <form action="{% url "app1:upload" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>

        <p></p>
        <hr>

        {% for row in excel_data %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}
    </body>
</html>